### ISSUE TITLE
Adding unnamed Point of Interests to a File 

### ISSUE THREAD

**Issue by N3XT191** [gpxstudio/gpx.studio#15]
Many Point of Interests don't have an explicit name (Most Water sources don't for example). When adding them to a file, they get added without a name (since they don't have any...)

I think it would be nice to label them with their category (so in this case just "Water"). Would make it easier to navigate large numbers of saved POIs.

<img width="419" alt="Screenshot 2024-07-18 at 14 04 20" src="https://github.com/user-attachments/assets/cf5f8210-2773-4847-ab1d-8f2c49ed6f2b">

It is also possible to add the same point multiple times to the same file. I don't see a practical use for this and think it might be nice to block these duplicates.

<img width="120" alt="Screenshot 2024-07-18 at 14 05 14" src="https://github.com/user-attachments/assets/150fbaee-a367-4434-b707-cf90d0ec080e">

**Comment by N3XT191** [comment]
Additionally, it would be nice to color the waypoints (=added points of interest) in the same color as the paths:

<img width="539" alt="Screenshot 2024-07-18 at 14 32 09" src="https://github.com/user-attachments/assets/453b2f56-c34d-4d33-91e3-f0daef6a586b">

(My use case for this is that I'm preparing separate files for Water, Accommodation, Resupply which I'll then export to the app I'll use for navigation. It's easier to keep the overview in the editor if I can see which point is which category.)

**Comment by vcoppe** [comment]
> I think it would be nice to label them with their category (so in this case just "Water"). Would make it easier to navigate large numbers of saved POIs.

Done. When the POI has no name field, I have also used the category name as title of the popup.

> Additionally, it would be nice to color the waypoints (=added points of interest) in the same color as the paths:

I have added that but I am not completely satisfied with the design. Let me know if you have other ideas.

**Comment by N3XT191** [comment]
Hmm, I think it's better already, but still not super easy to differentiate.

I played around with the CSS a bit and think this would look great for the case where you have lots of pins of different colours:

<img width="246" alt="Screenshot 2024-07-19 at 10 08 13" src="https://github.com/user-attachments/assets/c9ec0004-07c5-4f5c-95bb-0cdd25a3a151">

(I simply changed the 2 fill colours and the outer stroke colour to black)

<path fill="orange" stroke="black" stroke-width="1" d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"></path>
<circle fill="orange" stroke="white" stroke-width="2.5" cx="12" cy="10" r="3"></circle>

But this way it might look very dark if you have a dark line colour and 100 pins of the same colour close together. So not sure if this is good for all use cases.
